# -*- coding: utf-8 -*-
"""get_scholar_profiles_final.ipynb

Automatically generated by Colab.
"""

import sys
from scholarly import scholarly
import pandas as pd

# Function to get scholar profiles and save to an Excel file
def get_scholar_profiles(input_file, output_file='profiles.xlsx'):
    try:
        with open(input_file, 'r') as file:
            researcher_names = [line.strip() for line in file.readlines()]
    except FileNotFoundError:
        print(f"Error: The file {input_file} was not found.")
        return

    profiles = []
    for name in researcher_names:
        try:
            search_query = scholarly.search_author(name)
            author = next(search_query)
            profiles.append(scholarly.fill(author))
        except StopIteration:
            profiles.append({})

    pd.DataFrame(profiles).to_excel(output_file, index=False)
    print(f"Profiles saved to {output_file}")

if __name__ == "__main__":
    if len(sys.argv) not in [2, 3]:
        print("Usage: python get_scholar_profiles.py <input_file> [<output_file>]")
    else:
        input_file = sys.argv[1]
        output_file = sys.argv[2] if len(sys.argv) == 3 else 'profiles.xlsx'
        get_scholar_profiles(input_file, output_file)
